/**
 * The route/link parser.
 *
 * Links arrive from outside the app — typed, pasted, or generated by another
 * tool — so the interesting half of these tests is the malformed half: every
 * one of them must come back as a refusal, never a throw.
 */
import { describe, it, expect } from 'vitest'
import {
  PAGES,
  parseDeepLink,
  formatDeepLink,
  navLabelForRoute,
  routeForNavLabel,
  type DeepLink,
} from './route'

const PROJECT = '0f3a5a1e-6a2b-4a1e-9d5c-2f0b1c7d8e90'

function parsed(url: string): DeepLink {
  const result = parseDeepLink(url)
  if (!result.ok) throw new Error(`expected a link, got: ${result.reason}`)
  return result.link
}

describe('parseDeepLink', () => {
  it('reads a ticket link by human id, not uuid', () => {
    expect(parsed(`overhead://project/${PROJECT}/ticket/OVH-123`)).toEqual({
      projectUuid: PROJECT,
      target: { kind: 'ticket', ticketId: 'OVH-123' },
    })
  })

  it('uppercases a ticket id that lost its case in transit', () => {
    expect(parsed(`overhead://project/${PROJECT}/ticket/ovh-123`).target)
      .toEqual({ kind: 'ticket', ticketId: 'OVH-123' })
  })

  it('reads a page link for every page', () => {
    for (const page of PAGES) {
      expect(parsed(`overhead://project/${PROJECT}/page/${page}`).target)
        .toEqual({ kind: 'page', page })
    }
  })

  it('reads the notes page, which the navbar reaches by the same route', () => {
    expect(parsed(`overhead://project/${PROJECT}/page/notes`).target)
      .toEqual({ kind: 'page', page: 'notes' })
  })

  it('reads a graph view link', () => {
    expect(parsed(`overhead://project/${PROJECT}/view/v-77`).target)
      .toEqual({ kind: 'view', viewUuid: 'v-77' })
  })

  it('tolerates a trailing slash, a query and a fragment', () => {
    expect(parsed(`overhead://project/${PROJECT}/page/execute/`).target)
      .toEqual({ kind: 'page', page: 'execute' })
    expect(parsed(`overhead://project/${PROJECT}/page/execute?from=cli#top`).target)
      .toEqual({ kind: 'page', page: 'execute' })
  })

  it('accepts the scheme and keywords in any case', () => {
    expect(parsed(`OVERHEAD://PROJECT/${PROJECT}/PAGE/Backlog`)).toEqual({
      projectUuid: PROJECT,
      target: { kind: 'page', page: 'backlog' },
    })
  })

  it('decodes percent-encoded segments', () => {
    expect(parsed('overhead://project/a%20b/view/v%2F1')).toEqual({
      projectUuid: 'a b',
      target: { kind: 'view', viewUuid: 'v/1' },
    })
  })
})

describe('parseDeepLink — refusals', () => {
  const bad: [string, string][] = [
    ['garbage',              'not a url at all'],
    ['',                     'the empty string'],
    ['https://example.com/project/x/page/home', 'a foreign scheme'],
    ['overhead://',          'nothing after the scheme'],
    ['overhead://project',   'no project uuid'],
    [`overhead://project/${PROJECT}`,            'no target'],
    [`overhead://project/${PROJECT}/ticket`,     'a target with no value'],
    [`overhead://project/${PROJECT}/page/kanban`, 'a page that does not exist'],
    [`overhead://project/${PROJECT}/note/n-1`,   'a target kind that does not exist'],
    [`overhead://board/${PROJECT}/page/home`,    'a root that is not a project'],
    [`overhead://project/${PROJECT}/page/home/extra`, 'more segments than the scheme has'],
    ['overhead://project/%E0%A4%A/page/home',    'broken percent-encoding'],
  ]

  for (const [url, why] of bad) {
    it(`refuses ${why}`, () => {
      const result = parseDeepLink(url)
      expect(result.ok).toBe(false)
      if (result.ok) return
      expect(result.reason.length).toBeGreaterThan(0)
    })
  }

  it('refuses rather than throwing on non-string input', () => {
    expect(parseDeepLink(undefined as unknown as string).ok).toBe(false)
    expect(parseDeepLink(42 as unknown as string).ok).toBe(false)
  })
})

describe('formatDeepLink', () => {
  const links: DeepLink[] = [
    { projectUuid: PROJECT, target: { kind: 'ticket', ticketId: 'OVH-123' } },
    { projectUuid: PROJECT, target: { kind: 'page', page: 'execute' } },
    { projectUuid: PROJECT, target: { kind: 'page', page: 'graph' } },
    { projectUuid: PROJECT, target: { kind: 'view', viewUuid: 'v-77' } },
    { projectUuid: 'a b',   target: { kind: 'view', viewUuid: 'v/1' } },
  ]

  it('writes the documented shape', () => {
    expect(formatDeepLink(links[0])).toBe(`overhead://project/${PROJECT}/ticket/OVH-123`)
    expect(formatDeepLink(links[1])).toBe(`overhead://project/${PROJECT}/page/execute`)
    expect(formatDeepLink(links[3])).toBe(`overhead://project/${PROJECT}/view/v-77`)
  })

  it('round-trips every link kind', () => {
    for (const link of links) {
      expect(parsed(formatDeepLink(link))).toEqual(link)
    }
  })
})

describe('navbar labels', () => {
  it('round-trips every page and overlay label', () => {
    for (const label of ['Home', 'Product', 'Explore', 'Execute', 'Backlog', 'All', 'Graph', 'Notes']) {
      const route = routeForNavLabel(label)
      expect(route).not.toBeNull()
      expect(navLabelForRoute(route!)).toBe(label)
    }
    for (const label of ['Settings', 'Archived', 'Projects']) {
      expect(routeForNavLabel(label)).toEqual({ kind: 'overlay', overlay: label.toLowerCase() })
    }
  })

  it('shows a ticket under All and a graph view under Graph', () => {
    expect(navLabelForRoute({ kind: 'ticket', uuid: 't-1' })).toBe('All')
    expect(navLabelForRoute({ kind: 'view', viewUuid: 'v-1' })).toBe('Graph')
  })

  it('returns null for a label that is not a route', () => {
    expect(routeForNavLabel('Kanban')).toBeNull()
    expect(routeForNavLabel('')).toBeNull()
  })
})
